=== BeatrizOliveira262/Portfolio/Projects/Project_7/Grupo_1.dtd
<!ELEMENT TEI (teiHeader, text)>
<!ATTLIST TEI xmlns CDATA #IMPLIED>

<!ELEMENT teiHeader (fileDesc)>
<!ELEMENT fileDesc (titleStmt, publicationStmt, sourceDesc)>

<!ELEMENT titleStmt (author| title| respStmt)*>
<!ELEMENT author (#PCDATA | hi)*>
<!ELEMENT hi (#PCDATA | drug | lb | locus | geoName | condition | precaution | result | intervention | ingredient | dosage | ew | pc | term)*>
<!ATTLIST hi rend (bold | italic) #IMPLIED>
<!ELEMENT title (#PCDATA | pc | hi)*>
<!ATTLIST title type CDATA #IMPLIED>
<!ELEMENT respStmt (resp, name+)>
<!ELEMENT resp (#PCDATA)>
<!ELEMENT name (#PCDATA)>

<!ELEMENT publicationStmt (p+)>
<!ELEMENT sourceDesc (bibl)>
<!ELEMENT bibl (#PCDATA | term | lb | choice | reg | orig | title | author | pubPlace | date | publisher)*>
<!ELEMENT pubPlace (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>

<!ELEMENT text (body)>
<!ELEMENT body (div+)>
<!ELEMENT div (head | p+ | pb* | figure | graphic)*>
<!ATTLIST div style CDATA #IMPLIED>
<!ELEMENT head (hi+ | lb | locus | drug)*>
<!ATTLIST head type CDATA #IMPLIED>
<!ATTLIST head n CDATA #IMPLIED>
<!ELEMENT n (#PCDATA)>
<!ELEMENT p (#PCDATA | hi | figure | graphic | choice | reg | orig | precaution | lb | pc | geoName | drug | condition | patient | locus | time | prep-med | ingredient | excipient | herb | dosage | ew | result | intervention | pb | bibl | term)*>
<!ATTLIST p n CDATA #IMPLIED>
<!ATTLIST p hi CDATA #IMPLIED>
<!ELEMENT pc (#PCDATA)>
<!ELEMENT choice (orig, reg)>
<!ELEMENT orig (#PCDATA | pc | lb)*>
<!ELEMENT reg (#PCDATA | pc | lb)*>
<!ELEMENT figure (graphic)>
<!ELEMENT graphic EMPTY>
<!ATTLIST graphic url CDATA #REQUIRED>
<!ELEMENT pb EMPTY>
<!ATTLIST pb n CDATA #REQUIRED>
<!ELEMENT lb EMPTY>

<!ELEMENT term (#PCDATA)>
<!ATTLIST term rend (italic) #IMPLIED>

<!ELEMENT drug (#PCDATA | lb | pc | ew | pb | figure | graphic)*>
<!ELEMENT condition (#PCDATA | lb | locus | pc | ew | pb | figure | graphic)*>
<!ELEMENT patient (#PCDATA | condition | pc | lb)*>
<!ELEMENT locus (#PCDATA)>
<!ELEMENT geoName (#PCDATA | pc | lb)*>
<!ELEMENT time (#PCDATA | lb | pc)*>
<!ELEMENT ew (#PCDATA | pc)*>
<!ELEMENT result (#PCDATA | condition | intervention | patient | lb | pc | excipient | locus | choice | reg | orig)*>
<!ELEMENT intervention (#PCDATA | prep-med | ingredient | time | condition | patient | drug | dosage | pc | locus | lb | result | excipient)*>
<!ELEMENT precaution (#PCDATA | pc | dosage | drug | geoName | patient | condition | result | intervention | lb | ingredient | pb)*>
<!ELEMENT prep-med (#PCDATA | ingredient | drug | dosage | excipient | herb | lb | result | pc | ew | time | figure | graphic | choice | reg | orig | pb)*>
<!ELEMENT ingredient (#PCDATA | drug | herb | excipient | dosage | time | lb | choice | reg | orig)*>
<!ELEMENT excipient (#PCDATA | pc | lb | choice | reg | orig)*>
<!ELEMENT herb (#PCDATA | lb | pc)*>
<!ELEMENT dosage (#PCDATA | pc | lb | excipient | choice | reg | orig)*>

=== BeatrizOliveira262/Portfolio/Projects/Project_7/Grupo_1.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE TEI SYSTEM "Grupo_1.dtd">

<TEI xmlns="http://www.tei-c.org/ns/1.0">
	<teiHeader>
		<fileDesc>
			<titleStmt>
				<title><hi rend="bold">MEMORIAL DE VARIOS SIMPLICES</hi></title>
				<title type="sub">
					Que da Índia oriental, da América, e de outras partes do mundo vêm ao nosso Reino para remédio de muitas doenças, no qual se acharão as virtudes de cada um, e o modo com que se devem usar.
				</title>
				<author><hi rend="bold">CURVO SEMMEDO</hi></author>
				<respStmt>
					<resp>Transcrição efetuada por</resp>
					<name>Beatriz Oliveira</name>
					<name>Micaelly Caldeira</name>
					<name>Ana Maciel</name>
				</respStmt>
			</titleStmt>
			<publicationStmt>
				<p>Trabalho académico realizado na Unidade Curricular de Edição Digital.</p>
				<p>Obra publicada pela primeira vez na 3.ª edição da Polyanthea Medicinal em 1716.</p>
			</publicationStmt>
			<sourceDesc>
				<bibl>
					<title>Memória de varios simplices</title>
					<author>João Curvo Semmedo</author>
					<pubPlace>Lisboa</pubPlace>
					<date>Entre 1700 e 1799</date>
					<publisher>não identificado</publisher>
				</bibl>
			</sourceDesc>
		</fileDesc>
	</teiHeader>
	<text>
        	 <body>
        	    <div style="text-align: center;">
           <figure>
              <graphic url="foto1.jpg" />
           </figure>
        	<head n="1"><hi rend="bold"><drug>PEDRA BAZAR SIMPLEZ.</drug></hi></head>
        	<head type="sub"><hi rend="italic">Regimento, e virtudes da <drug>Pedra Bazar Simplez</drug>, ou natural, que n[s]ce nos<lb/>
            <locus>buchos de huns animaes muy [s]emelhantes aos cabritos.</locus>
            </hi></head>

        	<p n="1">
        	            <hi rend="bold">P</hi>Rimeiramente <choice><orig>he</orig><reg>é</reg></choice> <choice><orig>nece[ss]ario</orig><reg>necessário</reg></choice> examinar com grande cuidado <choice><orig>[s]e</orig><reg>se</reg></choice> a <drug>Pedra Bazar</drug> <choice><orig>he</orig><reg>é</reg></choice> ver<pc>-</pc><lb/>
        	            dadeira, ou <choice><orig>fal[s]a</orig><reg>falsa</reg></choice>, porque, <choice><orig>[s]e</orig><reg>se</reg></choice> <choice><orig>he</orig><reg>é</reg></choice> verdadeira, obra excelentes efeitos, com tal <choice><orig>condi<pc>-</pc><lb/>
        	                çaõ</orig><reg>condição</reg></choice>, que <choice><orig>[s]e</orig><reg>se</reg></choice><intervention> deve dar em quantidade <dosage> vinte e quatro grãos</dosage> de cada vez </intervention>, porque, dando só<pc>-</pc><lb/>
        	            mena <dosage><choice><orig>tres</orig><reg>três</reg></choice>, ou quatro grãos</dosage>, como <choice><orig>co[s]tumaõ</orig><reg>costumam</reg></choice> dar os barbeiros, que <choice><orig>[s]aõ</orig><reg>são</reg></choice> os Medicos da <lb/>
        	            gente ordinaria, <result>nenhum <choice><orig> effeito </orig><reg> efeito </reg></choice> faz</result>, pela pouca quantidade em que a <choice><orig>daõ</orig><reg>dão</reg></choice>, e <choice><orig> de[s]te </orig><reg> deste </reg></choice> modo<lb/>
        	            <result>fica o remedio infamado, a vida do <patient>doente</patient> perdida, e o dinheiro mal <choice><orig> ga[s]tado </orig><reg> gasto </reg></choice></result>; e <choice><orig>naõ</orig><reg>não</reg></choice> <choice><orig>[s]uc<pc>-</pc><lb/>
        	                cederia</orig><reg>sucederia</reg></choice> <choice><orig>a[ss]im </orig><reg> assim </reg></choice>, <choice><orig>[s]e</orig><reg>se</reg></choice> a pedra <choice><orig> fo[ss]e</orig><reg> fosse</reg></choice> verdadeira, e a <choice><orig> de[ss]em </orig><reg>dessem </reg></choice>  na quantidade <choice><orig>[s]obredita </orig><reg>sobredita </reg></choice>. 
        	        </p>
        	        
        <p n="2">
        	            <choice><orig>He</orig><reg>É</reg></choice> <choice><orig> nece[ss]ario </orig><reg> necessário </reg></choice> que os Medicos principiantes <choice><orig> advirtaõ </orig><reg> advirtão </reg></choice> duas <choice><orig> cousas </orig><reg> coisas </reg></choice> muito importantes,<lb/>
        	            A primeira, que <prep-med>a dita <drug>pedra</drug><choice><orig> [s]e </orig><reg> se </reg></choice> deve <choice><orig> mi[s]turar </orig><reg> misturar </reg></choice><ingredient> <dosage>cinco, ou  <choice><orig>[s]eis </orig><reg> seis </reg></choice> onças</dosage> de <excipient>agua commua</excipient></ingredient><lb/>
        	                cozida com <herb>e[s]corcioneira</herb>, ou com <herb>papoulas</herb>, ou com <herb>cardo [s]anto</herb></prep-med>, porque os que <choice><orig> daõ </orig><reg> dão </reg></choice> a di<pc>-</pc><lb/>
        	            ta <drug>pedra</drug> mi[s]turada com <ingredient><excipient>aguas <choice><orig> de[s]tilladas </orig><reg> destiladas </reg></choice></excipient></ingredient>, <result> <choice><orig> erraõ </orig><reg> errão </reg></choice> o alvo em claro</result>, pelas <choice><orig> razoens </orig><reg> razões </reg></choice> que os<choice><orig> cu<pc>-</pc><lb/>
        	                rio[s]os </orig><reg> curiosos</reg></choice> podem ver na minha <bibl> <term rend="italic">Polyanthea</term> da terceira <choice><orig> impre[ss]aõ </orig><reg> impressão </reg></choice> trat. 2. cap. 130. fol. 675. n.1.</bibl>
        	        </p>
        	        
		<p n="3">
						A [s]egunda cou[s]a, que devem  advertir os que derem <prep-med> a dita <drug>pedra</drug>, he, que a mi[s]turem<lb/>
					    <ingredient><dosage>cinco ou ꭍeis onças </dosage>de <excipient>agua cõmua</excipient></ingredient> cozida com qualquer das cou[s]as [s]obreditas;</prep-med> por<pc>-</pc><lb/>
						que os que a daõ <prep-med>mi[s]turada com <dosage>duas colheres de <excipient>agua</excipient></dosage>, como fazem os barbeiros, <result>tambem<lb/>
						erraõ o alvo, porque taõ pouca quantidade de <excipient>agua</excipient> naõ he vehiculo ba[s]tante para levar<lb/>
						a pedra aos lugares di[s]tantes aonde he de [s]ervir</result>; mas mi[s]turando-a com <dosage> grande quantida<pc>-</pc><lb/>
						de de <excipient>agua</excipient></dosage></prep-med>,<result> faz muito bons efeitos nas <condition>ancias do coraçaõ</condition>, nos <condition>vàgados</condition>, nas <condition>faltas de re[s]<pc>-</pc><lb/>
					    piraçaõ</condition>, e em todas as <condition>febres agudas, e malignas</condition></result>, dando-a a qualquer hora que a nece[ss]i<pc>-</pc><lb/>
						dade o pedir, e [s]obre <intervention>[s]angrias</intervention>.
					</p>
	
           <figure>
              <graphic url="foto2.jpg" />
          	
           </figure>
        	    	
		<p n="4">
					Nas <condition><locus>[s]uppre[ss]oens altas da ourina</locus></condition> tem a <drug>pedra Bazar</drug>, [s]endo verdadeira, grande virtude,<lb/>
					com tal condiçaõ,  que antes de applicar, <intervention>façaõ tomar ao <patient> doente </patient>hum vomitorio</intervention> de <prep-med><ingredient><dosage>tres<lb/>
					onças </dosage> de <drug>agua Benedicta</drug></ingredient>, ou <ingredient>de<dosage> [s]eis grãos</dosage> de <drug>Tartaro emetico</drug></ingredient>, ou <ingredient><dosage>de meya oitava</dosage> de <drug>ca<pc>-</pc><lb/>
					parro[s]a branca</drug></ingredient></prep-med>, <intervention>[s]angrando-o <time> ao outro dia nos braços quatro vezes, ao outro dia tres, e ao<lb/>
					outro outras tres,</time></intervention> porque como e[s]te ca[s]o he taõ perigo[s]o, e apre[ss]ado, he nece[ss]ario faze<pc>-</pc><lb/>
					rem [s]e os remedios com grande brevidade, porque [s]e naõ ourinaõ atè o <time>[s]eptimo dia</time>, or<pc>-</pc><lb/>
					dinariamente <result>morrem</result>: e por e[s]ta razaõ requeiro da parte de Deos aos Medicos principian<pc>-</pc><lb/>
					tes, que comecem infallivelmente a cura das <condition>[s]uppre[ss]oens, [s]ejaõ <locus>altas</locus>, ou <locus>baixas</locus></condition>, por <intervention>vo<pc>-</pc><lb/>
				    mitorios</intervention>, e <intervention>[s]angrias repetidas nos <locus>braços</locus></intervention>; porque e[s]te con[s]elho [s]e funda na experiencia<lb/>
					de cincoenta e oito annos, e nas muitas <condition>[s]uppre[ss]oens</condition> que curey felizmente por e[s]te e[s]tylo<lb/>
					como os curio[s]os pódem ver na minha <bibl><term rend="italic"> Polyanthea</term> d, terceira impre[ss]aõ trat.2. cap.83 fol.<lb/>
					448. n. 37. v[s]q. ad49</bibl>. aonde acharàõ nomeados os <patient> doentes</patient> que curey de <condition>[s]uppre[ss]oens</condition><lb/>
					por e[s]te e[s]tylo e[s]tando alguns delles ungidos quando me chamàraõ.
			</p>
	
		<p n="5">
					Permita-[s]-me haver feito e[s]ta digre[ss]aõ, porque me obriga o zelo da vida dos proxi<pc>-</pc><lb/>
					mos, a dar e[s]te avi[s]o taõ importante aos pre[s]entes, e os futuros Medicos.
			</p>
	
		<p n="6">
					Tornando ao propo[s]ito da <drug>Pedra Bazar</drug>, digo, que depois de dados os <intervention>vomitorios</intervention>, e <lb/>
				    <intervention>[s]angrias <locus>altas</locus></intervention>, que [s]aõ remedios preci[s]amente nece[ss]arios para curar as <condition>[s]uppre[ss]oens da<lb/>
				    ourina</condition>, [s]e dara a tal <prep-med><ingredient><drug>pedra</drug> em <dosage> quantidade de vinte e quatro, ou de quarenta grãos</dosage></ingredient> mi[s]<pc>-</pc><lb/>
					turados com <ingredient> <dosage>oito onças</dosage> de <excipient>agua quente</excipient></ingredient>, que primeiro [s]eja cozida <ingredient>com <dosage> huma onça </dosage>de <herb>pào <lb/>
					de faveira [s]eca</herb></ingredient>, e em falta delle,<ingredient> com <dosage> meya onça </dosage>de <drug>eroca marinha</drug></ingredient>, e em falta de[s]ta com<lb/>
					<dosage>duas oitavas</dosage> de <herb>erva [s]apinha</herb>, e melhor que tudo, com <dosage>meya onça</dosage> de erva chamada<lb/>
